name: "Install Tools"
description: "Install various tools, executables, and utilities not normally present in GitHub Actions' Windows runners."

inputs:
  pkgconf:
    description: "Install pkgconf (aka pkg-config)"
    type: bool
    default: false
  zstd:
    description: "Install zstandard (aka zstd)"
    type: bool
    default: false
  vulkan:
    description: "Install Vulkan Loader + Headers"
    type: bool
    default: false

runs:
  using: "composite"
  steps:
    - name: Install pkgconf
      if: inputs.pkgconf == 'true'
      shell: cmd
      run: |
        cd "${{ github.action_path }}"
        sh -e pkgconf.sh

    - name: Install zstd
      if: inputs.zstd == 'true'
      shell: cmd
      run: |
        cd "${{ github.action_path }}"
        sh -e zstd.sh

    - name: Install vulkan
      if: inputs.vulkan == 'true'
      shell: cmd
      run: |
        cd "${{ github.action_path }}"
        sh -e vulkan.sh
