name: Test Action

on: [pull_request, push, workflow_dispatch]

jobs:
  test:
    name: Test (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
          - os: windows-11-arm

    steps:
      - name: Install all tools
        uses: crueter-ci/install-tools@master
        with:
          pkgconf: true
          zstd: true
          vulkan: true
          nasm: true
          ffnvcodec: true
          gas-preprocessor: true

      - name: Check
        shell: bash
        run: |
          zstd --version
          pkgconf --version
          gas-preprocessor.pl -help
          echo "$VULKAN_SDK"

          if [ "${{ matrix.os }}" = windows-latest ]; then
            nasm --version
          fi

          export PKG_CONFIG_PATH="$FFNVCODEC_DIR/lib/pkgconfig"
          printf -- "-- ffnvcodec pkg-config: "
          pkg-config --cflags --libs ffnvcodec

          export PKG_CONFIG_PATH="$VULKAN_SDK/lib/pkgconfig"
          printf -- "-- vulkan pkg-config: "
          pkg-config --cflags --libs vulkan

          echo
          echo "$PATH"