name: Test Action

on: [pull_request, push, workflow_dispatch]

jobs:
  test:
    name: Test (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
          - os: windows-11-arm

    steps:
      - name: Install all tools
        uses: crueter-ci/install-tools@master
        with:
          pkgconf: true
          zstd: true
          vulkan: true
          nasm: true
          ffnvcodec: true

      - name: Check
        shell: bash
        run: |
          zstd --version
          pkgconf --version
          echo "$VULKAN_SDK"
          nasm --version || true

          export PKG_CONFIG_PATH="$FFNVCODEC_DIR"
          pkg-config --cflags ffnvcodec

          echo
          echo "$PATH"